//! Rust-shaped data-parallel compute on Apple Metal.
//!
//! This is an early implementation slice. It currently supports synchronous,
//! shape-preserving `parallel_iter().map().collect()` kernels on shared tensors.

#[cfg(not(target_os = "macos"))]
compile_error!("parallel-metal currently requires macOS and Metal");

extern crate self as parallel_metal;

mod error;
mod extent;
mod runtime;
mod tensor;

pub use error::{Error, Result};
pub use extent::{Extent, Point};
pub use parallel_metal_macros::parallel;
pub use tensor::{MetalElement, Tensor};

#[deprecated(since = "0.1.0", note = "renamed to the shorter Tensor<T, D>")]
pub type UnifiedTensor<T, const D: usize> = Tensor<T, D>;

/// Runtime details used by code generated by `#[parallel]`.
///
/// This module is public only because procedural macro expansions are compiled
/// in the caller's crate. Its API is not stable.
#[doc(hidden)]
pub mod __private {
    pub use crate::runtime::{BufferBinding, ScalarBinding, execute_elementwise};
}
